export const RECIPE_CATEGORIES = [
  "Beef", "Chicken", "Dessert", "Lamb", "Miscellaneous", 
  "Pasta", "Pork", "Seafood", "Side", "Starter", 
  "Vegan", "Vegetarian", "Breakfast", "Goat"
];

// Extracted from the API strArea JSON 
export const RECIPE_AREAS = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguan, Barbudan",
  "Argentine",
  "Armenian",
  "Aruban",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Bosnian, Herzegovinian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdian",
  "Caymanian",
  "Central African",
  "Chadian",
  "Channel Islander",
  "Chilean",
  "Chinese",
  "Colombian",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "Ecuadorean",
  "Egyptian",
  "Emirati",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Gibraltar",
  "Greek",
  "Greenlandic",
  "Grenadian",
  "Guadeloupian",
  "Guamanian",
  "Guatemalan",
  "Guinean",
  "Guinea-Bissauan",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hong Konger",
  "Hungarian",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kirghiz",
  "Kosovar",
  "Kuwaiti",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivan",
  "Malian",
  "Maltese",
  "Mauritian",
  "Mexican",
  "Moldovan",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nepalese",
  "New Zealander",
  "Ni-Vanuatu",
  "Nicaraguan",
  "Nigerien",
  "Nigerian",
  "North Korean",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Puerto Rican",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Sammarinese",
  "Samoan",
  "Saudi Arabian",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovene",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swedish",
  "Swiss",
  "Syrian",
  "Tadzhik",
  "Taiwanese",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Yemeni",
  "Zambian",
  "Zimbabwean"
];

export const AREAS_AND_COUNTRIES = {
  "Afghan": "Afghanistan",
  "Albanian": "Albania",
  "Algerian": "Algeria",
  "American": "United States",
  "Andorran": "Andorra",
  "Angolan": "Angola",
  "Antiguan, Barbudan": "Antigua and Barbuda",
  "Argentine": "Argentina",
  "Armenian": "Armenia",
  "Aruban": "Aruba",
  "Australian": "Australia",
  "Austrian": "Austria",
  "Azerbaijani": "Azerbaijan",
  "Bahamian": "Bahamas",
  "Bahraini": "Bahrain",
  "Bangladeshi": "Bangladesh",
  "Barbadian": "Barbados",
  "Belarusian": "Belarus",
  "Belgian": "Belgium",
  "Belizean": "Belize",
  "Beninese": "Benin",
  "Bermudian": "Bermuda",
  "Bhutanese": "Bhutan",
  "Bolivian": "Bolivia",
  "Bosnian, Herzegovinian": "Bosnia and Herzegovina",
  "Brazilian": "Brazil",
  "British": "United Kingdom",
  "Bruneian": "Brunei",
  "Bulgarian": "Bulgaria",
  "Burkinabe": "Burkina Faso",
  "Burmese": "Myanmar",
  "Burundian": "Burundi",
  "Cambodian": "Cambodia",
  "Cameroonian": "Cameroon",
  "Canadian": "Canada",
  "Cape Verdian": "Cape Verde",
  "Caymanian": "Cayman Islands",
  "Central African": "Central African Republic",
  "Chadian": "Chad",
  "Channel Islander": "Channel Islands",
  "Chilean": "Chile",
  "Chinese": "China",
  "Colombian": "Colombia",
  "Congolese": "Democratic Republic of the Congo",
  "Costa Rican": "Costa Rica",
  "Croatian": "Croatia",
  "Cuban": "Cuba",
  "Cypriot": "Cyprus",
  "Czech": "Czech Republic",
  "Danish": "Denmark",
  "Djibouti": "Djibouti",
  "Dominican": "Dominican Republic",
  "Dutch": "Netherlands",
  "Ecuadorean": "Ecuador",
  "Egyptian": "Egypt",
  "Emirati": "United Arab Emirates",
  "Equatorial Guinean": "Equatorial Guinea",
  "Eritrean": "Eritrea",
  "Estonian": "Estonia",
  "Ethiopian": "Ethiopia",
  "Faroese": "Faroe Islands",
  "Fijian": "Fiji",
  "Filipino": "Philippines",
  "Finnish": "Finland",
  "French": "France",
  "Gabonese": "Gabon",
  "Gambian": "Gambia",
  "Georgian": "Georgia",
  "German": "Germany",
  "Ghanaian": "Ghana",
  "Gibraltar": "Gibraltar",
  "Greek": "Greece",
  "Greenlandic": "Greenland",
  "Grenadian": "Grenada",
  "Guadeloupian": "Guadeloupe",
  "Guamanian": "Guam",
  "Guatemalan": "Guatemala",
  "Guinean": "Guinea",
  "Guinea-Bissauan": "Guinea-Bissau",
  "Guyanese": "Guyana",
  "Haitian": "Haiti",
  "Honduran": "Honduras",
  "Hong Konger": "Hong Kong",
  "Hungarian": "Hungary",
  "Icelander": "Iceland",
  "Indian": "India",
  "Indonesian": "Indonesia",
  "Iranian": "Iran",
  "Iraqi": "Iraq",
  "Irish": "Ireland",
  "Israeli": "Israel",
  "Italian": "Italy",
  "Ivorian": "Ivory Coast",
  "Jamaican": "Jamaica",
  "Japanese": "Japan",
  "Jordanian": "Jordan",
  "Kazakhstani": "Kazakhstan",
  "Kenyan": "Kenya",
  "Kirghiz": "Kyrgyzstan",
  "Kosovar": "Kosovo",
  "Kuwaiti": "Kuwait",
  "Laotian": "Laos",
  "Latvian": "Latvia",
  "Lebanese": "Lebanon",
  "Liberian": "Liberia",
  "Libyan": "Libya",
  "Liechtensteiner": "Liechtenstein",
  "Lithuanian": "Lithuania",
  "Luxembourger": "Luxembourg",
  "Macedonian": "North Macedonia",
  "Malagasy": "Madagascar",
  "Malawian": "Malawi",
  "Malaysian": "Malaysia",
  "Maldivan": "Maldives",
  "Malian": "Mali",
  "Maltese": "Malta",
  "Mauritian": "Mauritius",
  "Mexican": "Mexico",
  "Moldovan": "Moldova",
  "Mongolian": "Mongolia",
  "Montenegrin": "Montenegro",
  "Moroccan": "Morocco",
  "Mosotho": "Lesotho",
  "Motswana": "Botswana",
  "Mozambican": "Mozambique",
  "Namibian": "Namibia",
  "Nepalese": "Nepal",
  "New Zealander": "New Zealand",
  "Ni-Vanuatu": "Vanuatu",
  "Nicaraguan": "Nicaragua",
  "Nigerien": "Niger",
  "Nigerian": "Nigeria",
  "North Korean": "North Korea",
  "Norwegian": "Norway",
  "Omani": "Oman",
  "Pakistani": "Pakistan",
  "Palestinian": "Palestine",
  "Panamanian": "Panama",
  "Papua New Guinean": "Papua New Guinea",
  "Paraguayan": "Paraguay",
  "Peruvian": "Peru",
  "Polish": "Poland",
  "Portuguese": "Portugal",
  "Puerto Rican": "Puerto Rico",
  "Qatari": "Qatar",
  "Romanian": "Romania",
  "Russian": "Russia",
  "Rwandan": "Rwanda",
  "Saint Lucian": "Saint Lucia",
  "Salvadoran": "El Salvador",
  "Sammarinese": "San Marino",
  "Samoan": "Samoa",
  "Saudi Arabian": "Saudi Arabia",
  "Senegalese": "Senegal",
  "Serbian": "Serbia",
  "Seychellois": "Seychelles",
  "Sierra Leonean": "Sierra Leone",
  "Singaporean": "Singapore",
  "Slovak": "Slovakia",
  "Slovene": "Slovenia",
  "Solomon Islander": "Solomon Islands",
  "Somali": "Somalia",
  "South African": "South Africa",
  "South Korean": "South Korea",
  "South Sudanese": "South Sudan",
  "Spanish": "Spain",
  "Sri Lankan": "Sri Lanka",
  "Sudanese": "Sudan",
  "Surinamer": "Suriname",
  "Swedish": "Sweden",
  "Swiss": "Switzerland",
  "Syrian": "Syria",
  "Tadzhik": "Tajikistan",
  "Taiwanese": "Taiwan",
  "Tanzanian": "Tanzania",
  "Thai": "Thailand",
  "Togolese": "Togo",
  "Tongan": "Tonga",
  "Trinidadian": "Trinidad and Tobago",
  "Tunisian": "Tunisia",
  "Turkish": "Turkey",
  "Turkmen": "Turkmenistan",
  "Tuvaluan": "Tuvalu",
  "Ugandan": "Uganda",
  "Ukrainian": "Ukraine",
  "Uruguayan": "Uruguay",
  "Uzbekistani": "Uzbekistan",
  "Venezuelan": "Venezuela",
  "Vietnamese": "Vietnam",
  "Yemeni": "Yemen",
  "Zambian": "Zambia",
  "Zimbabwean": "Zimbabwe"
};